name: patrol_devtools_extension
description: A new Flutter project.
publish_to: none

version: 0.3.0

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  devtools_app_shared: ^0.1.1
  devtools_extensions: ^0.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  json_annotation: ^4.8.1
  vm_service: ^14.2.1

dev_dependencies:
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  leancode_lint: ^12.1.0

flutter:
  uses-material-design: true
