name: patrol_log
description: >
  Log package for Patrol, a powerful Flutter-native UI testing framework.
version: 0.4.0
homepage: https://patrol.leancode.co
repository: https://github.com/leancodepl/patrol/tree/master/packages/patrol_log
issue_tracker: https://github.com/leancodepl/patrol/issues
documentation: https://patrol.leancode.co
topics: [test, log, patrol]

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  dispose_scope: ^2.1.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  fake_async: ^1.3.1
  json_serializable: ^6.8.0
  leancode_lint: ^14.3.0
  mocktail: ^1.0.1
  test: ^1.24.9
