name: patrol_cli
description: >
  Command-line tool for Patrol, a powerful Flutter-native UI testing framework.
version: 1.1.3 # Must be kept in sync with constants.dart
homepage: https://patrol.leancode.co
repository: https://github.com/leancodepl/patrol
issue_tracker: https://github.com/leancodepl/patrol/issues

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  adb: ^0.2.5
  ansi_styles: ^0.3.2
  args: ^2.4.0
  cli_completion: ^0.3.0
  collection: ^1.17.1
  dispose_scope: ^2.0.1
  equatable: ^2.0.5
  file: ^6.1.4
  freezed_annotation: ^2.2.0
  glob: ^2.1.1
  http: ^0.13.5
  mason_logger: ^0.2.4
  meta: ^1.9.0
  path: ^1.8.3
  platform: ^3.1.0
  process: ^4.2.4
  pub_updater: ^0.2.4
  tuple: ^2.0.1
  unified_analytics: ^0.1.2
  yaml: ^3.1.1
dev_dependencies:
  build_runner: ^2.3.3
  fake_async: ^1.3.1
  freezed: ^2.3.2
  leancode_lint: ^2.1.0
  mocktail: ^0.3.0
  test: ^1.23.1

executables:
  patrol: main
