name: patrol_cli
description: >
  Command-line tool for Patrol, a powerful Flutter-native UI testing framework.
version: 3.6.0-dev.1  # Must be kept in sync with constants.dart
homepage: https://patrol.leancode.co
repository: https://github.com/leancodepl/patrol/tree/master/packages/patrol_cli
issue_tracker: https://github.com/leancodepl/patrol/issues?q=is%3Aopen+is%3Aissue+label%3A%22package%3A+patrol_cli%22
documentation: https://patrol.leancode.co
topics: [test, cli, patrol]
screenshots:
  - description: The Patrol framework logo.
    path: screenshots/logo.png

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  adb: ^0.5.0
  ansi_styles: ^0.3.2+1
  args: ^2.4.2
  ci: ^0.1.0
  cli_completion: ^0.4.0
  collection: ^1.18.0
  coverage: ^1.9.0
  dispose_scope: ^2.1.0
  equatable: ^2.0.5
  file: ^7.0.0
  glob: ^2.1.2
  http: ^1.1.0
  mason_logger: ^0.2.10
  meta: ^1.10.0
  package_config: ^2.1.1
  path: ^1.8.3
  patrol_log: ^0.4.0
  platform: ^3.1.3
  process: ^5.0.1
  pub_updater: ^0.4.0
  uuid: ^4.2.1
  version: ^3.0.2
  vm_service: ^14.2.4
  yaml: ^3.1.2
dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.7.0
  fake_async: ^1.3.1
  leancode_lint: ^14.3.0
  mocktail: ^1.0.1
  test: ^1.24.9

executables:
  patrol: main
