name: patrol_cli
description: >
  Command-line tool for Patrol, a powerful Flutter-native UI testing framework.
version: 0.6.14
homepage: https://patrol.leancode.co
repository: https://github.com/leancodepl/patrol
issue_tracker: https://github.com/leancodepl/patrol/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  adb: ^0.2.1+2
  ansi_styles: ^0.3.2+1
  archive: ^3.3.1
  args: ^2.3.1
  collection: ^1.16.0
  dispose_scope: ^2.0.0
  file: ^6.1.4
  freezed_annotation: ^2.1.0
  http: ^0.13.5
  logging: ^1.0.2
  mason_logger: ^0.1.3
  meta: ^1.8.0
  path: ^1.8.2
  platform: ^3.1.0
  pub_updater: ^0.2.2
  yaml: ^3.1.1
dev_dependencies:
  build_runner: ^2.2.1
  fake_async: ^1.3.1
  freezed: ^2.1.0+1
  leancode_lint: ^1.3.0
  mocktail: ^0.3.0
  test: ^1.21.4

executables:
  patrol: main
