name: patrol_mcp
description: MCP server for managing Patrol develop sessions for Flutter projects.
version: 0.3.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  adb: ^0.6.0
  args: ^2.7.0
  dispose_scope: ^2.1.0
  image: ^4.5.4
  logging: ^1.3.0
  mcp_dart: ^1.2.2
  path: ^1.9.1
  patrol_cli:
    path: ../patrol_cli

dev_dependencies:
  leancode_lint: ^17.0.0

executables:
  patrol_mcp: patrol_mcp
