name: maestro_cli
description: CLI for Maestro.
version: 0.1.4
homepage: https://github.com/leancodepl/maestro

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  adb: ^0.0.3
  ansi_styles: ^0.3.2+1
  args: ^2.3.1
  http: ^0.13.4
  logging: ^1.0.2
  mason_logger: ^0.1.0-dev.10
  path: ^1.8.2
  toml: ^0.12.0
  yaml: ^3.1.1
dev_dependencies:
  leancode_lint: ^1.1.0
  test: ^1.21.1

executables:
  maestro: main
