name: adb
description: Simple Dart wrapper around Android Debug Bridge.
version: 0.5.0
repository: https://github.com/leancodepl/patrol/tree/master/packages/adb
issue_tracker: https://github.com/leancodepl/patrol/issues?q=is%3Aopen+is%3Aissue+label%3A%22package%3A+adb%22

environment:
  sdk: '>=3.5.0 <4.0.0'

dev_dependencies:
  custom_lint: ^0.6.4
  leancode_lint: ^14.2.0
  mocktail: ^1.0.1
  test: ^1.24.9

executables:
  dadb: example
