name: adb
description: Simple Dart wrapper around Android Debug Bridge.
version: 0.2.0
repository: https://github.com/leancodepl/maestro
issue_tracker: https://github.com/leancodepl/maestro/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  mocktail: ^0.3.0
  path: ^1.8.2

dev_dependencies:
  leancode_lint: ^1.2.1
  test: ^1.21.5

executables:
  dadb: example
