name: patrol_example
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.0+1
  flutter_timezone: ^1.0.7
  geolocator: ^9.0.2
  permission_handler: ^10.4.2
  timezone: ^0.9.2
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  leancode_lint: ^3.0.0
  patrol:
    path: ../

flutter:
  uses-material-design: true

patrol:
  app_name: Patrol example
  android:
    package_name: pl.leancode.patrol.example
  ios:
    bundle_id: pl.leancode.patrol.Example
  macos:
    bundle_id: pl.leancode.patrol.macos.example
