name: example
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  convenient_test: ^1.2.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^11.0.0
  geolocator: ^9.0.1
  permission_handler: ^10.0.0
  webview_flutter: ^3.0.4

dev_dependencies:
  convenient_test_dev: ^1.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  leancode_lint: ^1.3.0
  patrol:
    path: ../

flutter:
  uses-material-design: true
