name: patrol_finders
description: Streamlined, high-level API on top of flutter_test.
version: 2.8.2
homepage: https://patrol.leancode.co
repository: https://github.com/leancodepl/patrol/tree/master/packages/patrol_finders
issue_tracker: https://github.com/leancodepl/patrol/issues?q=is%3Aopen+is%3Aissue+label%3Apackage%3Apatrol_finders
documentation: https://patrol.leancode.co
topics: [test, widget-test, patrol]
screenshots:
  - description: The Patrol framework logo.
    path: screenshots/logo.png

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.10.0
  patrol_log: ^0.4.0

dev_dependencies:
  leancode_lint: ^14.3.0
