name: patrol_finders
description: Streamlined, high-level API on top of `flutter_test`.
version: 1.0.0
homepage: https://patrol.leancode.co
repository: https://github.com/leancodepl/patrol
issue_tracker: https://github.com/leancodepl/patrol/issues

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.16.0-0.3.pre'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  leancode_lint: ^3.0.0
