name: automatorserver release

on:
  workflow_dispatch:
  push:
    tags:
      - "automatorserver-v*"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: AutomatorServer

    env:
      SERVER_FILE: server-${{ github.ref_name }}.apk
      INSTRUMENTATION_FILE: instrumentation-${{ github.ref_name }}.apk
      AZURE_STORAGE_URL: https://lncdmaestrostorage.blob.core.windows.net/artifacts
      AZURE_SAS_TOKEN: ${{ secrets.AZURE_SAS_TOKEN }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build server APK
        run: |
          ./gradlew assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk $SERVER_FILE

      - name: Build instrumentation APK
        run: |
          ./gradlew assembleDebugAndroidTest
          mv app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk $INSTRUMENTATION_FILE

      - name: Create release on GitHub Actions
        uses: softprops/action-gh-release@v1
        with:
          name: "AutomatorServer ${{ github.ref_name }}"
          files: |
            $SERVER_FILE
            $INSTRUMENTATION_FILE

      - name: Upload artifacts to Azure Storage
        run: |
          ./deploy "$SERVER_FILE"
          ./deploy "$INSTRUMENTATION_FILE"
