name: integration test ios

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  main:
    name: "Test on iOS (${{ matrix.device }}, ${{ matrix.os }} ${{ matrix.os_version }})"
    runs-on: macos-latest
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        flutter-channel: [stable]
        device: ["iPhone 14", "iPad (9th generation)"]
        os: ["iOS"]
        os_version: ["16.2"]

    defaults:
      run:
        working-directory: packages/patrol/example

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter-channel }}

      - name: Preload Flutter artifacts
        run: flutter precache

      - name: Install Patrol
        run: dart pub global activate patrol_cli

      - uses: futureware-tech/simulator-action@v2
        with:
          model: ${{ matrix.device }}
          os: ${{ matrix.os }}
          os_version: ${{ matrix.os_version }}
          erase_before_boot: true
          shutdown_after_job: true

      - name: Run example test
        run: |
          cd ios

          flutter build ios --config-only integration_test/example_test.dart --debug --simulator
          xcodebuild test \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -xcconfig Flutter/Debug.xcconfig \
            -configuration Debug \
            -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14" \
            OTHER_SWIFT_FLAGS='$(inherited) -D PATROL_ENABLED'

          flutter build ios --config-only integration_test/features/services/dark_mode_test.dart --debug --simulator
          xcodebuild test \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -xcconfig Flutter/Debug.xcconfig \
            -configuration Debug \
            -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14" \
            OTHER_SWIFT_FLAGS='$(inherited) -D PATROL_ENABLED'

          flutter build ios --config-only integration_test/features/permissions/permissions_test.dart --debug --simulator
          xcodebuild test \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -xcconfig Flutter/Debug.xcconfig \
            -configuration Debug \
            -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14" \
            OTHER_SWIFT_FLAGS='$(inherited) -D PATROL_ENABLED'

          # # Fails on CI: cannot tap on "Open" button in the notification
          # flutter build ios --config-only integration_test/features/notifications/notifications_single_test.dart --debug --simulator
          # xcodebuild test \
          #   -workspace Runner.xcworkspace \
          #   -scheme Runner \
          #   -xcconfig Flutter/Debug.xcconfig \
          #   -configuration Debug \
          #   -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14" \
          #   OTHER_SWIFT_FLAGS='$(inherited) -D PATROL_ENABLED'
