name: maestro_cli prepare

on:
  push:
    branches: [main]
    ignore-tags: ["maestro_cli-v*"]
    paths:
      - "packages/maestro_cli/**"
  pull_request:
    branches: [main]
    paths:
      - "packages/maestro_cli/**"

jobs:
  main:
    name: Dart ${{ matrix.sdk }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        sdk: [2.16.2, stable]

    defaults:
      run:
        working-directory: packages/maestro_cli

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ matrix.sdk }}

      - name: dart version
        run: dart --version

      - name: dart pub get
        run: dart pub get

      - name: dart analyze
        run: dart analyze

      # We don't have any tests, yet.
      # - name: dart test
      #   run: dart test

      - name: dart format
        run: dart format --set-exit-if-changed .
