name: maestro_test prepare

on:
  workflow_dispatch:
  pull_request:

jobs:
  main:
    name: Flutter ${{ matrix.channel }}${{ matrix.version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - version: "2.10.0"
          - channel: stable
          - channel: beta

    defaults:
      run:
        working-directory: packages/maestro_test

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}
          flutter-version: ${{ matrix.version }}

      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: flutter version
        run: flutter --version

      - name: flutter pub get
        run: flutter pub get

      - name: flutter analyze
        run: flutter analyze --no-fatal-infos

      # We don't have any tests, yet.
      # - name: flutter test
      #   run: flutter test

      - name: flutter format (example app)
        run: cd example && flutter format --set-exit-if-changed .

      - name: flutter pub get (example app)
        run: cd example && flutter pub get

      - name: flutter analyze (example app)
        run: cd example && flutter analyze --no-fatal-infos

      - name: flutter format (example app)
        run: cd example && flutter format --set-exit-if-changed .
