name: maestro_cli prepare

on:
  push:
    branches: [master]
    ignore-tags: ["maestro_cli-v*"]
    paths:
      - "packages/maestro_cli/**"
      - "AutomatorServer/**"
  pull_request:
    branches: [master]
    paths:
      - "packages/maestro_cli/**"
      - "AutomatorServer/**"

jobs:
  main:
    name: Dart ${{ matrix.sdk }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        sdk: [2.16.2, stable]

    defaults:
      run:
        working-directory: packages/maestro_cli

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ matrix.sdk }}

      - name: dart version
        run: dart --version

      - name: dart pub get
        run: dart pub get

      - name: dart analyze
        run: dart analyze

      # We don't have any tests, yet.
      # - name: dart test
      #   run: dart test

      - name: dart format
        run: dart format --set-exit-if-changed .

      - name: ktlint check
        working-directory: ./AutomatorServer
        run: ./gradlew ktlintCheck

      - name: ktlint format
        working-directory: ./AutomatorServer
        run: ./gradlew ktlintFormat

      - name: Test maestro bootstrap --template generic
        working-directory: ../
        run: |
          flutter create my_awesome_app
          cd my_awesome_app
          maestro bootstrap --template generic
          flutter analyze

      - name: Test maestro bootstrap --template counter
        working-directory: ../
        run: |
          flutter create example
          cd example
          maestro bootstrap --template generic
          flutter analyze
