name: maestro_test prepare

on:
  push:
    branches: [master]
    tags-ignore: ["maestro_test-v*"]
    paths:
      - "packages/maestro_test/**"
  pull_request:
    branches: [master]
    paths:
      - "packages/maestro_test/**"

jobs:
  main:
    name: Flutter ${{ matrix.channel }}${{ matrix.version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 2.10.5
          - channel: stable
          - channel: beta

    defaults:
      run:
        working-directory: packages/maestro_test

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
          flutter-version: ${{ matrix.version }}

      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: flutter version
        run: flutter --version

      - name: flutter pub get
        run: flutter pub get

      - name: flutter format
        run: flutter format --set-exit-if-changed .

      - name: flutter analyze
        run: flutter analyze

      - name: flutter test
        run: flutter test

      - name: flutter pub get (example app)
        working-directory: ./packages/maestro_test/example
        run: flutter pub get

      - name: flutter format (example app)
        working-directory: ./packages/maestro_test/example
        run: flutter format --set-exit-if-changed .

      - name: flutter analyze (example app)
        working-directory: ./packages/maestro_test/example
        run: flutter analyze --no-fatal-infos

      - name: flutter test (example app)
        working-directory: ./packages/maestro_test/example
        run: flutter test
