name: patrol_cli prepare

on:
  push:
    branches: [master]
    tags-ignore: ['*']
    paths:
      - 'packages/patrol_cli/**'
  pull_request:
    branches: [master]
    paths:
      - 'packages/patrol_cli/**'

jobs:
  main:
    name: Flutter ${{ matrix.flutter-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        flutter-version: ['3.3.x', '3.7.x']
        include:
          - os: ubuntu-latest
            flutter-version: '3.10.0-1.5.pre'
            channel: beta
          - os: windows-latest
            flutter-version: '3.10.0-1.5.pre'
            channel: beta

    defaults:
      run:
        working-directory: packages/patrol_cli

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
          flutter-version: ${{ matrix.flutter-version }}

      - name: dart pub get
        run: dart pub get

      - name: Build executable
        run: dart pub global activate --source path .

      - name: Run executable (smoke test)
        run: patrol

      - name: dart test
        run: |
          dart test --coverage coverage
          dart run coverage:format_coverage --lcov --in coverage --out coverage/lcov.info --report-on lib

      - name: dart analyze
        run: dart analyze

      - name: dart format
        run: dart format --set-exit-if-changed .

      - name: dart pub publish --dry-run
        run: dart pub publish --dry-run
