name: patrol_gen prepare

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/patrol_gen/**'

jobs:
  prepare:
    name: Dart ${{ matrix.dart-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dart-version: ['3.1']

    defaults:
      run:
        working-directory: packages/patrol_gen

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.dart-version }}

      - name: dart pub get
        run: dart pub get

      - name: dart analyze
        if: success() || failure()
        run: dart analyze

      - name: dart format
        if: success() || failure()
        run: dart format --set-exit-if-changed .
