name: testlab android

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  main:
    name: "Test on Android on Firebase Test Lab"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    defaults:
      run:
        working-directory: packages/patrol/example

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_JSON }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          generate-job-summary: false

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter-channel }}

      - name: Preload Flutter artifacts
        run: flutter precache

      - name: Generate Gradle wrapper
        run: flutter build apk --debug --flavor=does-not-exist || true

      # TODO: Parallelize running on Firebase Test Lab with Flank

      - name: Run example_test.dart
        run: ./run_android_testlab integration_test/example_test.dart
        if: success() || failure()

      - name: Run app_test.dart
        run: ./run_android_testlab integration_test/app_test.dart
        if: success() || failure()

      - name: Run notifications_single_test.dart
        run: ./run_android_testlab integration_test/notifications_single_test.dart
        if: success() || failure()

      # TODO: Enable again when flakiness is fixed
      # - name: Run notifications_many_test.dart
      #   run: ./run_android_testlab integration_test/notifications_many_test.dart
      #   if: success() || failure()

      - name: Run open_app_test.dart
        run: ./run_android_testlab integration_test/open_app_test.dart
        if: success() || failure()

      - name: Run open_quick_settings_test.dart
        run: ./run_android_testlab integration_test/open_quick_settings_test.dart
        if: success() || failure()
