name: maestro_test
description: >
  Simple, easy-to-learn, Flutter-native UI testing framework eliminating
  limitations of flutter_driver
version: 0.2.0
homepage: https://github.com/leancodepl/maestro/tree/main/packages/maestro_test

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  freezed_annotation: ^1.1.0
  http: ^0.13.4
  json_annotation: ^4.5.0
  logging: ^1.0.2

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^1.1.1
  json_serializable: ^6.2.0
  leancode_lint: ^1.1.0
  test: ^1.21.1
